### ISSUE TITLE
[CRASH] Weird crash.

### ISSUE THREAD

**Issue by ToadStar** [Laike-Endaril/Dynamic-Stealth#1]
Not quite sure how to describe it, but here's the crashlog for posterity:

`java.lang.NullPointerException: Ticking entity
	at net.minecraft.world.World.func_189509_E(World.java:225)
	at net.minecraft.world.World.func_180495_p(World.java:905)
	at net.minecraft.pathfinding.PathNavigateGround.func_179680_a(SourceFile:44)
	at com.fantasticsource.dynamicstealth.newai.AISearchLastKnownPosition.newPath(AISearchLastKnownPosition.java:254)
	at com.fantasticsource.dynamicstealth.newai.AISearchLastKnownPosition.func_75246_d(AISearchLastKnownPosition.java:143)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:885)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2351)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43)
	at nmd.primal.core.common.entities.living.EntityGator.func_70636_d(EntityGator.java:239)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2171)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)`

https://pastebin.com/iughf8xu

**Comment by Laike-Endaril** [comment]
Thanks for the report!  This should be fixed in 008 (I will close the issue once 008 is released)

Fix commit: https://github.com/Laike-Endaril/Dynamic-Stealth/commit/46c817e935d337fd435ed9b25eabea58f77ab555
