### ISSUE TITLE
Crash with AOA3

### ISSUE THREAD

**Issue by SilenceJhin** [Laike-Endaril/Dynamic-Stealth#109]
My game always crash when the flying entities from AOA3 appeared.
The crash report：
 at net.tslat.aoa3.entity.base.ai.mob.EntityAIFlyingRangedAttack.updateTask(EntityAIFlyingRangedAttack.java:33)
    at net.minecraft.entity.ai.EntityAITasks.onUpdateTasks(SourceFile:129)
    at net.minecraft.entity.EntityLiving.updateEntityActionState(EntityLiving.java:888)
    at net.minecraft.entity.EntityLivingBase.onLivingUpdate(EntityLivingBase.java:2359)
    at net.minecraft.entity.EntityLiving.onLivingUpdate(EntityLiving.java:678)
    at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2179)
    at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:377)
    at net.tslat.aoa3.entity.base.AoAFlyingRangedMob.onUpdate(AoAFlyingRangedMob.java:339)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1958)
    at net.minecraft.world.World.redirect$zbe000$updateEntity(World.java:4123)
    at net.minecraft.world.World.updateEntities(World.java:1762)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)

**Comment by Laike-Endaril** [comment]
In the DS config, go to (server settings -> AI -> add null checks to AI) and add the AI class from the crash report: net.tslat.aoa3.entity.base.ai.mob.EntityAIFlyingRangedAttack

Then restart server (or client if on single player/LAN) and see if it fixes the issue

**Comment by SilenceJhin** [comment]
It got solved,thank U so much

**Comment by SilenceJhin** [comment]
It got solved if I add mobID to (server settings->Entity-Specific Full Bypass).But it not work to when I add (aoa3, net.tslat.aoa3.entity.base.ai.mob.EntityAIFlyingRangedAttack) to (server settings -> AI -> add null checks to AI).

**Comment by SilenceJhin** [comment]
I think I'm not understand how to edit the parameter format of (server settings -> AI -> add null checks to AI) perhaps.

**Comment by SilenceJhin** [comment]
By the way,I tried (aoa3, net.tslat.aoa3.entity.base.ai.mob.EntityAIFlyingRangedAttack) and ( net.tslat.aoa3.entity.base.ai.mob.EntityAIFlyingRangedAttack),both of them were not work

**Comment by SilenceJhin** [comment]
It got solved,thank U so much
