### ISSUE TITLE
Crash in SpongeForge

### ISSUE THREAD

**Issue by SettingDust** [Laike-Endaril/Dynamic-Stealth#113]
```
net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
	at net.minecraft.network.NetHandlerPlayServer.redirect$zil000$impl$onPlayerTick(NetHandlerPlayServer.java:2504) ~[pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.projectile.EntitySnowball.func_70016_h(DDD)V
	at com.fantasticsource.mctools.MCTools.spawnDebugSnowball(MCTools.java:547) ~[MCTools.class:?]
	at com.fantasticsource.mctools.MCTools.spawnDebugSnowball(MCTools.java:541) ~[MCTools.class:?]
	at com.fantasticsource.dynamicstealth.server.senses.sight.Sight.visualStealthLevelInternal(Sight.java:311) ~[Sight.class:?]
	at com.fantasticsource.dynamicstealth.server.senses.sight.Sight.visualStealthLevel(Sight.java:164) ~[Sight.class:?]
	at com.fantasticsource.dynamicstealth.server.senses.sight.Sight.visualStealthLevel(Sight.java:134) ~[Sight.class:?]
	at com.fantasticsource.dynamicstealth.server.senses.sight.Sight.seenEntitiesInternal(Sight.java:245) ~[Sight.class:?]
	at com.fantasticsource.dynamicstealth.server.senses.sight.Sight.seenEntities(Sight.java:228) ~[Sight.class:?]
	at com.fantasticsource.dynamicstealth.common.Network$VisibilityPacket.<init>(Network.java:140) ~[Network$VisibilityPacket.class:?]
	at com.fantasticsource.dynamicstealth.common.Network.sendClientData(Network.java:82) ~[Network.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_377_Network_sendClientData_PlayerTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:756) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:706) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:370) ~[FMLCommonHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_184808_cD(EntityPlayer.java:378) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
	... 10 more
```

**Comment by Laike-Endaril** [comment]
I believe I've fixed this in the indev version, and will release a new jar after looking into a few other things

**Comment by Laike-Endaril** [comment]
This should now be fixed in the latest release.  Please tell me if you test
