### ISSUE TITLE
Crash from Level Up Reloaded Compatibility

### ISSUE THREAD

**Issue by Ameranth** [Laike-Endaril/Dynamic-Stealth#122]
Hello again!

Sadly it seems that the new compatibility with Level Up is causing a crash:
`java.lang.IllegalArgumentException: argument type mismatch`

[here is the full crash log](https://pastebin.com/raw/MgJAKS1a), but this seems most relevant:
```
at com.fantasticsource.tools.ReflectionTool.invoke(ReflectionTool.java:205)
at com.fantasticsource.dynamicstealth.compat.CompatLevelUp2.stealthLevelVisMultiplier(CompatLevelUp2.java:32)
at com.fantasticsource.dynamicstealth.server.senses.sight.Sight.visualStealthLevelInternal(Sight.java:404)
at com.fantasticsource.dynamicstealth.server.senses.sight.Sight.visualStealthLevel(Sight.java:168)
at com.fantasticsource.dynamicstealth.server.senses.sight.Sight.canSee(Sight.java:121)
at com.fantasticsource.dynamicstealth.server.ai.edited.AIWatchClosestEdit.func_75250_a(AIWatchClosestEdit.java:85)
```

Perhaps the Level Up stealth level is stored as a float?

**Comment by Laike-Endaril** [comment]
This should not happen if you use the latest version of Level Up Reloaded (1.5.8)
You're currently on an older version (1.1.23)

**Comment by Ameranth** [comment]
Ah, fair enough; I had forgotten about not updating Level Up, as it has some questionable feature differences between versions.

Thank you for the reply!

**Comment by Laike-Endaril** [comment]
Hmm...well I'd suggest trying it out at least (the new version, that is).  Tell me how it works out, and your thoughts on the feature differences

**Comment by Laike-Endaril** [comment]
Ie. if there's a good enough reason to, I'll try adding support for a previous version.  But give the new one a good try first so I don't do it for no reason :P

**Comment by Ameranth** [comment]
No no don't worry about that, I'm happy giving it a try to have your mod working :)
I'm pretty sure Level Up can be altered to work more-or-less how I want anyway.

**Comment by Laike-Endaril** [comment]
Alright, well in that case I'll close this for now, but if anything else comes up, feel free to reply here and I'll see it (and re-open as necessary)
