### ISSUE TITLE
Ticking Block Entity

### ISSUE THREAD

**Issue by Fortist** [Laike-Endaril/Dynamic-Stealth#30]
Im unsure, was just in my Testing world.
But from what I gather, It probably has something to do with the Mob Farm I had set up with Industrial Foregoing.

```
---- Minecraft Crash Report ----
// But it works on my machine.

Time: 2019-02-18 09:12:24 EST
Description: Ticking block entity

java.lang.NullPointerException
    at net.minecraft.entity.player.EntityPlayerMP.onNewPotionEffect(EntityPlayerMP.java:1187)
    at net.minecraft.entity.EntityLivingBase.addPotionEffect(EntityLivingBase.java:751)
    at com.fantasticsource.dynamicstealth.common.DynamicStealth.entityDeath(DynamicStealth.java:315)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_371_DynamicStealth_entityDeath_LivingDeathEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:609)
    at net.minecraft.entity.EntityLivingBase.onDeath(EntityLivingBase.java:1168)
    at net.minecraft.entity.EntityLivingBase.attackEntityFrom(EntityLivingBase.java:1023)
    at net.minecraft.entity.monster.EntityMob.attackEntityFrom(EntityMob.java:70)
    at com.buuz135.industrial.tile.mob.MobRelocatorTile.lambda$work$4(MobRelocatorTile.java:125)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
    at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
    at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
    at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
    at java.util.stream.ReferencePipeline.forEach(Unknown Source)
    at com.buuz135.industrial.tile.mob.MobRelocatorTile.work(MobRelocatorTile.java:124)
    at com.buuz135.industrial.tile.WorkingAreaElectricMachine.performWork(WorkingAreaElectricMachine.java:112)
    at net.ndrei.teslacorelib.tileentities.ElectricMachine.protectedUpdate(ElectricMachine.kt:280)
    at com.buuz135.industrial.tile.CustomElectricMachine.protectedUpdate(CustomElectricMachine.java:120)
    at com.buuz135.industrial.tile.mob.MobRelocatorTile.protectedUpdate(MobRelocatorTile.java:95)
    at net.ndrei.teslacorelib.tileentities.ElectricTileEntity.innerUpdate(ElectricTileEntity.kt:118)
    at net.ndrei.teslacorelib.tileentities.SidedTileEntity.update(SidedTileEntity.kt:991)
    at net.minecraft.world.World.redirect$tileEntityUpdate$zcd000(World.java:4131)
    at net.minecraft.world.World.updateEntities(World.java:1835)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Block entity being ticked --
  Name: industrialforegoing:mob_relocator_tile // com.buuz135.industrial.tile.mob.MobRelocatorTile
  Block type: ID #3154 (tile.industrialforegoing.mob_relocator // com.buuz135.industrial.tile.block.MobRelocatorBlock // industrialforegoing:mob_relocator)
  Block data value: 4 / 0x4 / 0b0100
  Block location: World: (-100,65,-70), Chunk: (at 12,4,10 in -7,-5; contains blocks -112,0,-80 to -97,255,-65), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
  Actual block type: ID #3154 (tile.industrialforegoing.mob_relocator // com.buuz135.industrial.tile.block.MobRelocatorBlock // industrialforegoing:mob_relocator)
  Actual block data value: 4 / 0x4 / 0b0100
  Block Entity NBT: {tick_lastWork:4,paused:0b,addonItems:{Size:4,Items:[{Slot:0,id:"industrialforegoing:range_addon",Count:1b,Damage:1s},{Slot:1,id:"teslacorelib:energy_tier1",Count:1b,Damage:0s},{Slot:2,id:"teslacorelib:speed_tier1",Count:1b,Damage:0s},{Slot:3,id:"industrialforegoing:fluid_transfer_addon_push",Count:1b,tag:{ench:[{lvl:5s,id:32}]},Damage:4s}]},mob_relocator_out:{Size:12,Items:[{Slot:0,id:"minecraft:arrow",Count:64b,Damage:0s},{Slot:1,id:"minecraft:bone",Count:64b,Damage:0s},{Slot:2,id:"xreliquary:mob_ingredient",Count:38b,Damage:0s},{Slot:3,id:"minecraft:snow",Count:64b,Damage:0s},{Slot:4,id:"minecraft:pumpkin_pie",Count:64b,Damage:0s},{Slot:5,id:"thermalfoundation:material",Count:64b,Damage:194s},{Slot:6,id:"minecraft:gunpowder",Count:64b,Damage:0s},{Slot:7,id:"hmag:misc",Count:64b,Damage:0s},{Slot:8,id:"hmag:foodmisc",Count:64b,Damage:7s},{Slot:9,id:"minecraft:stick",Count:64b,Damage:0s},{Slot:10,id:"minecraft:gold_nugget",Count:64b,Damage:0s},{Slot:11,id:"bhc:red_heart",Count:64b,Damage:0s}]},fluidItems:{Size:2,Items:[]},work_energy:{TeslaCapacity:984L,TeslaOutput:0L,TeslaPower:984L,TeslaInput:60L},side_config:[{color:12,sides:[0,1,2,3,4,5]},{color:13,sides:[0,1,2,3,4,5]},{color:1,sides:[0,1,2,3,4,5]},{color:11,sides:[0,1,2,3,4,5]},{color:15,sides:[0,1,2,3,4,5]},{color:0,sides:[0,1,2,3,4,5]},{color:4,sides:[0,1,2,3,4,5]},{color:6,sides:[0,1,2,3,4,5]},{color:5,sides:[0,1,2,3,4,5]},{color:3,sides:[0,1,2,3,4,5]},{color:2,sides:[0,1,2,3,4,5]},{color:14,sides:[0,1,2,3,4,5]},{color:7,sides:[0,1,2,3,4,5]},{color:8,sides:[0,1,2,3,4,5]},{color:9,sides:[0,1,2,3,4,5]},{color:10,sides:[0,1,2,3,4,5]}],x:-100,y:65,z:-70,id:"industrialforegoing:mob_relocator_tile",tick_work:4,redstone:"AlwaysActive",inv_energy_items:{Size:2,Items:[]},fluids:{tanks:[{Empty:""}]},energy:{TeslaCapacity:50000L,TeslaOutput:0L,TeslaPower:50000L,TeslaInput:4000L}}
```

**Comment by Laike-Endaril** [comment]
Interesting...it's having an issue giving potion effects to the "player" which killed the mob.  I assume this is a fake player which is part of some kind of mob grinder / spike block or something?

**Comment by Laike-Endaril** [comment]
Yes, MobRelocatorTile uses a FakePlayer...I'll probably have to filter that out for applying potions.  This will probably be fixed in version 054 when it releases

**Comment by Laike-Endaril** [comment]
This should be fixed in the latest release (054).  If not, please post a new issue!
